### ISSUE TITLE
SublimeLinter 4 has breaking API changes

### ISSUE THREAD

**Issue by braver** [ckaznocha/SublimeLinter-contrib-write-good#11]
We're making big changes to SublimeLinter and some of it will break our interface with this particular plugin. You can have a look this change for how to prepare for this change:

https://github.com/SublimeLinter/SublimeLinter-phpmd/commit/ae3070586096114467c65d052f68ba872f2adc4b

**Comment by reagle** [comment]
Yea, most of my linters broke when SL4 was pushed via packagecontrol, very annoying. I'll have to somehow revert back to SL3 or home this package gets update.

**Comment by ChrisCummins** [comment]
Fixed as of #15, version 2.2.1.
