### ISSUE TITLE
Cannot locate write-good 

### ISSUE THREAD

**Issue by Kautenja** [ckaznocha/SublimeLinter-contrib-write-good#12]
I'm consistently getting a confusing error when ST3 starts up.

    WARNING: writegood cannot locate 'write-good'

I've tried uninstalling and reinstalling SublimeLinter and SublimeLinter-contrib-write-good from package control with no effect. Completely uninstalling ST3 and reinstalling it with only SublimeLinter and SublimeLinter-contrib-write-good reproduces the error consistently. write-good is certainly installed and up to date.

#### Versions

| | |
|:-:|:-:|
| OS  | MacOS 10.13.3 |
| ST3 | build 3143 |
| SublimeLinter | 4.0.2 |
| SublimeLinter-contrib-write-good | 2.2.0 |
| write-good | 0.11.3 |

----

This is the first issue I'm having with this package, having used it flawlessly for a long time. So, I'm assuming this is most likely due to breaking changes from SublimeLinter updating from `3.x` to `4.x`.

**Comment by Kautenja** [comment]
I've injected the fix proposed in #11 that seems to restore functionality of the package. I still get a warning on startup about write-good not being found, but the linter does seem to work after the first save trigger.

**Comment by ChrisCummins** [comment]
Fixed as of #15, version 2.2.1.
