### ISSUE TITLE
Use for "text" selector

### ISSUE THREAD

**Issue by alehandrof** [ckaznocha/SublimeLinter-contrib-write-good#2]
This linter seems to be hard-coded to only lint comments. That's fine for fine for source code, but I'd like to use it to lint markdown files (`text.html.markdown`). Is this possible?

(I've RTFM for SublimeLinter and only found how to map one syntax to another -- which doesn't apply in this case.)

**Comment by ckaznocha** [comment]
I played around with it a bit, using a * in the selector makes it tricky to specify a second selector an individual syntax in addition to the wild card. I think I can work around it by defining get_selectors(). I'll give it a shot when I have some time. PRs are welcome also!

**Comment by alehandrof** [comment]
I don't altogether follow your comment and I haven't used SublimeLinter in another context. But in ST source code is generally under the `source` selector and text is under `text`.

Will something like this work?:

```
 'source': 'comment'
 'text': '*'
```

**Comment by ckaznocha** [comment]
So the selector attribute takes dictionary with the keys being a syntax (like `markdown`) and the value being a selector (like `text.html.markdown`). There is a special wild card that applies a selector to all syntaxes but using it seems to disable other elements in the dictionary.

Ideally I would just set the value of * to be a tuple like this:
```python
selectors = {
        '*': ('comment', 'text')
    }
```
But SublimeLinter errors if the value isn't a string. The second best solution would be something like this:
```python
selectors = {
        '*': 'comment',
       'markdown': 'text'
    }
```
Setting it up like that I see the linter does to pass the content of the markdown file to write-good and get the results but for what ever reason it won't highlight anything in the markdown file itself.

The logic that tells SublimeLinter what selectors to use is in `get_selectors()` so I'm thinking if I re-define it I can get rid of the wild card and set the syntax to value of the currently open file. Then test if its markdown or something else when setting the selector. Make sense? I may also just try to submit a PR to SublimeLinter to support the first case.

**Comment by ckaznocha** [comment]
I stand corrected. I tried using scopes as the key's like in your example and that does indeed work.

Now, do you think it should check all text scopes or only markdown?

**Comment by alehandrof** [comment]
All text scopes makes sense, but I'll have to check what how it behaves when there's a mix of text and markup as in `text.html` and `text.tex.latex`.

**Comment by alehandrof** [comment]
I just had a quick look at a few HTML files and they look OK. They only thing the linter seems to catch is repetition (e.g., `</div></div>`).

This is fine for me. I plan to keep the linter disabled -- even when writing. I only want to see suggestions when revising. It would be distracting otherwise.

(I'd like to figure out a single command for toggling the linter. Right now I have to work through the SublimeLinter's menus. But that's another story.)

**Comment by ckaznocha** [comment]
Hm, I'm not seeing the same HTML behavior you are. Which version of write-good is installed? I think that might be annoying to folks who have to deal with messy HTML.

As for toggling the linter, I don't know of a way to do it directly but you may save your self some time by adding a user key binding for the toggle menu like this:

```JSON
    { "keys": ["ctrl+k", "t"], "command": "sublimelinter_toggle_linter", "args": {"which": "all"} }
```

**Comment by alehandrof** [comment]
I'm using the latest version of word-good (0.8.0). I checked some LaTeX files and there's some issues there as well. In the markup `\begin{enumerate}` write-good catches "enumerate" as wordy. It has a point :)

It's hard to know what will satisfy all users  -- especially since my guess is that most writerly folks would keep write-good disabled most of the time.

Two ideas:

- is it possible to add an editable option that defines the scopes for use with this linter?
- there's an SL option to [map one syntax name to another](http://www.sublimelinter.com/en/latest/global_settings.html?highlight=map%20syntax#syntax-map). I tried creating a fake scope called 'write-good' and then assigning it to, say, latex in the SL preferences like so: `"latex": "write-good"`. That w'rks, but it prevents the linter from checking _all_ source code comments.

P.S. About the toggling bit, I'll bother the SL folks.

**Comment by omgaz** [comment]
At the very least I think for plaintext files and markdown this would be very useful. HTML `text` could be trickier to deal with, but for writing (editing)… this is of great help :)

**Comment by ckaznocha** [comment]
I've tried to narrow the scope to include only actual text and not things like HTML tags. I hope this works for you. I've pushed the new version to package control.

**Comment by alehandrof** [comment]
It still catches HTML tags because they are, confusingly, a subset of the `text` scope.

A `<p>` tag for example is: `text.html.basic meta.tag.any.html entity.name.tag.html`

I don't mind for the reasons I mentioned above. I'm happy with fthe current functionality. Cheers.

**Comment by alehandrof** [comment]
I also opened [an issue](https://github.com/SublimeLinter/SublimeLinter3/issues/240) on the main linter repo for quickly toggling a specific linter.

**Comment by ckaznocha** [comment]
Yeah it is very odd how html is scoped. I still wasn't able to replicate the html tags getting highlighted, would you mind sending me the html file your using? If I can replicate I'll re-open this issue.

**Comment by alehandrof** [comment]
Try this:

```
<div>
<div>
</div>
</div>
```

It triggers repetition :)

You can exclude this by scoping for `text.html -meta.tag` (or some variation thereof). [ScopeHunter](https://github.com/facelessuser/ScopeHunter) is really useful for this job.

BTW, it's not that odd. The top-level `text` scope indicates markup, as opposed to source code, not plain text.
