### ISSUE TITLE
Avoid linting code

### ISSUE THREAD

**Issue by blakeembrey** [ckaznocha/SublimeLinter-contrib-write-good#6]
It never used to happen, but it looks like the scope change caused it to start linting code.

![image](https://cloud.githubusercontent.com/assets/1088987/7355692/ec27bfa0-ecf9-11e4-918d-7e4079039f22.png)

Current version: `v2.1.0`

Edit: FWIW, it's complaining the "authorize" is wordy or unneeded.

**Comment by Kristinita** [comment]
I want to use write-good only in text files, but not in source files. I think, it would be nice to add option `linter_syntax` like other linters, for example,

    "linter_syntax": ["MarkdownEditing/Markdown"]

And linter is used only for files and unsaved buffers with Markdown syntax.

Thanks.
