### ISSUE TITLE
Alternative to depending on global npm module

### ISSUE THREAD

**Issue by tomatau** [ckaznocha/SublimeLinter-contrib-write-good#7]
I'd really like to use this plugin but it depends on an npm package being installed globally.

As I'm using NVM to manage multiple versions of node - this will be a frustrating experience trying to lint text in different repositories!

Are there any alternatives? Could this plugin bundle a version of write-good instead? Write-good seems a bit inactive so I can't see them publishing it to brew on OSX or apt-get or something.

**Comment by ckaznocha** [comment]
Good idea @tomatau. The linter could be converted to a `node linter` making it so that it downloads the required npm packages its self eliminating the need for write-good to be installed globally. It will probably be a bit until I'm able to convert it but PRs are welcome!
